// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkxusivovghatuwmizhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtreHVzaXZvdmdoYXR1d21pemhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjEwNjQsImV4cCI6MjA2MzgzNzA2NH0.PVloJNR3FXDm8vgl5xGs4S625Ag3KK_wxR56xrY0RHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);